### ISSUE TITLE
i tried to run n this occured,

### ISSUE THREAD

**Issue by Aimannnhakim** [DariusAf/MesoNet#22]
Using TensorFlow backend.
Traceback (most recent call last):
  File "/home/aimannnhakim/PycharmProjects/project1/example.py", line 2, in <module>
    from classifiers import *
  File "/home/aimannnhakim/PycharmProjects/project1/classifiers.py", line 3, in <module>
    from keras.models import Model as KerasModel
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/__init__.py", line 3, in <module>
    from . import utils
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/utils/__init__.py", line 6, in <module>
    from . import conv_utils
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/utils/conv_utils.py", line 9, in <module>
    from .. import backend as K
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/backend/__init__.py", line 81, in <module>
    from .tensorflow_backend import *
  File "/home/aimannnhakim/PycharmProjects/MesoNet/venv/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 514
    """Returns whether `x` is a placeholder.
             ^
SyntaxError: invalid syntax

**Comment by DariusAf** [comment]
Hi,

As written, the bug comes from `python3.5/site-packages/keras/init.py`, I suggest you create an issue on the [Keras repository](https://github.com/keras-team/keras).
